version: "3"
services:
    web:
        # replace username/repo:tag with your name and image details
        image: genenetwork
        build: ./
        ports:
            - "1337:1337"
            - "80:80"
        depends_on:
            - redis
            - elasticsearch
            - predictionserver
            - pwaserver
        restart: always
        volumes:
            - "/data:/data"
        environment:
            - "discovery.zen.ping.unicast.hosts=elasticsearch"
            - ELASTICSEARCH_URL=http://elasticsearch:9200"
            - ELASTICSEARCH_HOST=elasticsearch
    redis:
        image: redis
        expose:
            - "6379"
        restart: always
    elasticsearch:
        image: elasticsearch:2.4
        expose:
            - "9200"
        restart: always
    predictionserver:
        image: predictionserver
        build: ./servers/PredictionServer/
        depends_on:
            - redis
            - elasticsearch
        volumes:
            - "/data:/data"
        restart: always
    pwaserver:
        image: pwaserver
        build: ./servers/PWAServer/
        depends_on:
            - redis
            - elasticsearch
        volumes:
            - "/data:/data"
        restart: always
